name: sdagroup0
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pip=24.3.1
  - pip:
    - pandas==2.2.3
    - numpy==2.1.3
    - matplotlib==3.9.3
    - plotly==5.24.1
    - geopandas==1.0.1
    - shapely==2.0.6
    - emoji==2.14.0
    - nltk==3.9.1
    - wordcloud==1.9.4
    - Pillow==11.0.0
    - textblob==0.18.0.post0
    - pickledb==0.9.2
    - PyQt5===5.15.11
    - langdetect==1.0.9
    - requests==2.32.3
    - pytest-shutil==1.8.1
    - pathlib==1.0.1