name: sdagroup0
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pip=24.3.1
  - pip:
    - pandas==2.2.3
    - numpy==2.0.2
    - matplotlib==3.9.3
    - scipy==1.14.1
    - scikit-learn==1.5.2
    - pickledb==0.9.2
    - plotly==5.24.1
    - geopandas==1.0.1
    - shapely==2.0.6
    - emoji==2.14.0
    - nltk==3.9.1
    - textblob==0.18.0.post0
    - wordcloud==1.9.4
    - pillow==10.4.0
    - PyQt5===5.15.11
    - requests==2.32.3
    - pytest-shutil==1.8.1
    - pathlib==1.0.1
    - fastdtw==0.3.4
    - tslearn==0.6.3
    - langid==1.1.6
    - moviepy==2.1.1
    - kaleido==0.2.1
    - statsmodels==0.14.4